export enum Action {
    EDIT_CATEGORY='EDIT_CATEGORY',
    EDITED_CATEGORY='EDITED_CATEGORY',
    EDIT_LOCATION='EDIT_LOCATION',
    EDITED_LOCATION='EDITED_LOCATION',
    CLOSE_CATEGORY_MODAL='CLOSE_CATEGORY_MODAL',
    CLOSE_LOCATION_MODAL='CLOSE_LOCATION_MODAL',
    REMOVE_CATEGORY='REMOVE_CATEGORY',
    REMOVE_LOCATION='REMOVE_LOCATION',
}
